"""Create Productos Table

Revision ID: 33430e6dfe16
Revises: 8c76ba02a8ff
Create Date: 2020-05-12 20:23:53.437121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33430e6dfe16'
down_revision = '8c76ba02a8ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto_model',
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('Referencia', sa.String(length=30), nullable=True),
    sa.Column('Precio', sa.Numeric(), nullable=True),
    sa.Column('Tamano', sa.Numeric(), nullable=True),
    sa.Column('Unidad', sa.String(length=30), nullable=True),
    sa.Column('idCategoria', sa.Integer(), nullable=True),
    sa.Column('idEstadoProducto', sa.Integer(), nullable=True),
    sa.Column('idUbicacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUbicacion'], ['Ubicacion.idUbicacion'], ),
    sa.PrimaryKeyConstraint('idProducto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_model')
    # ### end Alembic commands ###
