"""Create Ubiacion Table

Revision ID: 66f64131906f
Revises: 
Create Date: 2020-05-12 14:12:51.980407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f64131906f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ubicacion_model',
    sa.Column('idUbicacion', sa.Integer(), nullable=False),
    sa.Column('lugar', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('idUbicacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubicacion_model')
    # ### end Alembic commands ###
