"""Rename Ubicacion Table

Revision ID: 8c76ba02a8ff
Revises: 66f64131906f
Create Date: 2020-05-12 14:14:25.555676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c76ba02a8ff'
down_revision = '66f64131906f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ubicacion',
    sa.Column('idUbicacion', sa.Integer(), nullable=False),
    sa.Column('lugar', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('idUbicacion')
    )
    op.drop_table('ubicacion_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ubicacion_model',
    sa.Column('idUbicacion', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('lugar', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('idUbicacion'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('Ubicacion')
    # ### end Alembic commands ###
